spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/awp
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:/db/migration
    url: jdbc:postgresql://localhost:5432/awp
    driver-class-name: org.postgresql.Driver
    user: postgres
    password: postgres
    connect-retries: 60
    validate-on-migrate: true
    enabled: true
springdoc:
  swagger-ui: path=/swagger-ui.html

